language: generic

services:
  - docker

before_install:
  - docker build -t astrego/docker-react-okt-2020 -f Dockerfile.dev .

script:
  - docker run -e CI=true astrego/docker-react-okt-2020 npm run test
