services:
  - docker

language: go

deploy:
  provider: gae
  project: hellogo-147000
  keyfile: gce.json
  verbosity: debug
  on: master

before_install:
  - openssl aes-256-cbc -K $encrypted_62787b06b330_key -iv $encrypted_62787b06b330_iv
    -in tra.json.enc -out tra.json -d
